site_name: Alchemical 3D
site_dir: public

nav:
  - Home: index.md
  - Core Printer: core.md
  - Pestle Extruder: pestle.md
  - Retort Filament Dryer: retort.md

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]'

# Repository
repo_name: github.com/Alchemical-3D
repo_url: https://github.com/Alchemical-3D

theme:
  name: material
  logo: assets/images/alchemical-3d-icon.png
  palette:
    scheme: slate
    primary: pink
    accent: black
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list

extra:
  analytics:
    provider: google
    property: G-7CJPBHEEV7

  static_templates:
    - 404.html
